backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

# Dove salvare le immagini caricate dal CMS
media_folder: "public/assets"
public_folder: "/assets"

# Configurazione collezioni
collections:
  - name: "events"
    label: "Eventi"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}" # Usa il titolo come nome file
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Sottotitolo", name: "subtitle", widget: "string", required: false}
      - {label: "Data Evento", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false}
      - {label: "Luogo", name: "location", widget: "string", required: false}
      - {label: "Locandina", name: "poster", widget: "image", required: false}
      - {label: "Ãˆ un evento ARS CORI?", name: "isArsEvent", widget: "boolean", default: false}
      - {label: "Descrizione", name: "body", widget: "markdown"}